# Generated by Django 2.2.6 on 2019-11-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
                ('rodzaj', models.IntegerField(choices=[(4, 'Doramat'), (1, 'Komedia'), (3, 'Horror'), (0, 'Nieznany'), (2, 'S - F')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.ExtraInfo')),
            ],
        ),
    ]
