# Generated by Django 2.2.6 on 2019-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(4, 'Doramat'), (1, 'Komedia'), (3, 'Horror'), (2, 'S - F'), (0, 'Nieznany')], default=0),
        ),
    ]
