# Generated by Django 2.2.6 on 2019-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191120_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(4, 'Doramat'), (3, 'Horror'), (1, 'Komedia'), (0, 'Nieznany'), (2, 'S - F')], default=0),
        ),
    ]
