# Generated by Django 2.2.6 on 2019-11-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191120_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'S - F'), (3, 'Horror'), (0, 'Nieznany'), (4, 'Doramat'), (1, 'Komedia')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ExtraInfo'),
        ),
    ]
